name: ci
on: push
jobs: 
  ci:
    runs-on: ubuntu-latest
    steos: 
      - name: Chechout repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install 
      - name: Run test
        run: npm test 
